language: python
sudo: true
python:
  - "2.7"

install:
  - sudo apt-get install -y rpm

script:
  - pip freeze  # so to help eventual debug: know what exact versions are in use can be rather useful.

after_success:
  - echo "Packaging for BinTray - Debian..."
  - ./package.sh $TRAVIS_BRANCH $TRAVIS_PYTHON_VERSION deb
  - echo "Packaging for BinTray - RPM..."
  - ./package.sh $TRAVIS_BRANCH $TRAVIS_PYTHON_VERSION rpm

deploy:
  # PyPi deployment for tagged commits:
  # -> build a PyPi package when a version is set
  # Bintray deployment for develop branch and tagged commits:
  # -> build Deb/Rpm packages on develop branch or when a version is set
  - provider: pypi
    distributions: "sdist bdist_wheel"
    skip_existing: true
    on:
      tags: true
    user: alignak
    password:
      secure: "WAqQuk91d73QV27L5+56ax4CrfJO2NDMsimNqJkLUawqTUesXSZfsu26MX3TM+rCgl4yBXX5/vsSBvaTpxmB0L/GYkCyZoTN9g6L0kI1e8KU/p0o4S3R6pQ+DoleKnomSTiN05MwIwBtg/o6wOYpDCYZG78n6XXmL8OUJJwOO0dB1knna2d4GK/YmFWIA/csey7/Rk7KjEq7JS2a1MwiZbYaQkDTw7Xkr7eyTnErGLPh9SowSosvkkAEf7CqYn3e/IjUZlohW4eKvqtgZ95BLz18P8CGO2tlVRYCFFF3gWr20CnN+q0kPQuMRN80cuCf5h8uoUCNBvsTT/qwofzMqEjh9ADr3VhPjOGIB1qbzAjc0llor/Q5bSe30EPkotPzm3FRuv4KOurPl11SZwpmckgXJUv61ip8liVJOj2XWOwu8RhcI9rbLDuhyloUU4bfs/W0zNeCvz5BFXF73R2G1HShDNy7xISQJx9xgSCYHnPEiiytUPlzy9On69wCvEx7DiGI3SD9dPzSWtCx44HVyTBuwnF17VlodjYv+0wvOWO1RfR+exNyxkDxucz3UfAMLOuUaWsJ3/cjUDHC72PPORW9Tvmw0C5veQ8ThnYpHHympizz2GBD9XEhRWjo23CCIKYnNWuAo1pL3JqTm+SW0WQi6fsdt7MwXOO6qLMwcdU="
  - provider: bintray
    skip_cleanup: true
    file: dist/.bintray-deb.json
    user: mohierf
    key:
      secure: "E7gQCt2UO1zR3zc7UUQM9iJdF1ZrFUZd8i2ssuMhbXe3YrhmVQo20gXvB6si0U4G4iy5bHT3TB5r5Q7JBiyNazwgxHZb2XnNo368YrPEtVGZ6pOYC2/bL4MkjkFVPtOggtoTP57Mu/UN4MHhFmkjaSLfpLWPpBOFvHflOzF5cz9Z8RcIbFRRaaoQPxmplTxgFd1eEJ7Su4+1J8BJA+cxha9mvfquccTGcp0H+ZXnWrwMPiWbthMtBPY/9DfDXWAyf2rLASBxzJMrhr9wy7eAKeIqNcVlXzH/Q6g4Jxf5mNa0zJfcBTSC+GW9+PAOrs/rFsIp0hpSmq8hgtr56DldCIK0sh86qVjtt4hLJ4CXB7uyqxMEx9uV1jscnTSIlfdoJKIiP24XH8ownslRhgOqJqAyNSxmWnEsWgZfPNBVwsn85VTLpC3hEJKFvgYM3WSiYG8Qq9ui8NtZho+XddiCg9BlYD+MAJ48iwSq7UBZVCGwm4OlVZF8PWnJMf0s4X3NR41PpPP7O/S0X/jnPAGJwgeBvskUpNJu6JHufwoEoZfMXTeZez+UCbDLzZmaV4gex9ylXlIgnYhCLB0PpopFT13USaLmUD02Lx5wm+trivdvMI0XgdGfy+UOpHrziuEZA/2DehJS7zusf6dPSXmMU7EP2dmCHhWt5H6eauO1s5M="
    on:
      all_branches: true
  - provider: bintray
    skip_cleanup: true
    file: dist/.bintray-deb.json
    user: mohierf
    key:
      secure: "E7gQCt2UO1zR3zc7UUQM9iJdF1ZrFUZd8i2ssuMhbXe3YrhmVQo20gXvB6si0U4G4iy5bHT3TB5r5Q7JBiyNazwgxHZb2XnNo368YrPEtVGZ6pOYC2/bL4MkjkFVPtOggtoTP57Mu/UN4MHhFmkjaSLfpLWPpBOFvHflOzF5cz9Z8RcIbFRRaaoQPxmplTxgFd1eEJ7Su4+1J8BJA+cxha9mvfquccTGcp0H+ZXnWrwMPiWbthMtBPY/9DfDXWAyf2rLASBxzJMrhr9wy7eAKeIqNcVlXzH/Q6g4Jxf5mNa0zJfcBTSC+GW9+PAOrs/rFsIp0hpSmq8hgtr56DldCIK0sh86qVjtt4hLJ4CXB7uyqxMEx9uV1jscnTSIlfdoJKIiP24XH8ownslRhgOqJqAyNSxmWnEsWgZfPNBVwsn85VTLpC3hEJKFvgYM3WSiYG8Qq9ui8NtZho+XddiCg9BlYD+MAJ48iwSq7UBZVCGwm4OlVZF8PWnJMf0s4X3NR41PpPP7O/S0X/jnPAGJwgeBvskUpNJu6JHufwoEoZfMXTeZez+UCbDLzZmaV4gex9ylXlIgnYhCLB0PpopFT13USaLmUD02Lx5wm+trivdvMI0XgdGfy+UOpHrziuEZA/2DehJS7zusf6dPSXmMU7EP2dmCHhWt5H6eauO1s5M="
    on:
      tags: true
  - provider: bintray
    skip_cleanup: true
    file: dist/.bintray-rpm.json
    user: mohierf
    key:
      secure: "E7gQCt2UO1zR3zc7UUQM9iJdF1ZrFUZd8i2ssuMhbXe3YrhmVQo20gXvB6si0U4G4iy5bHT3TB5r5Q7JBiyNazwgxHZb2XnNo368YrPEtVGZ6pOYC2/bL4MkjkFVPtOggtoTP57Mu/UN4MHhFmkjaSLfpLWPpBOFvHflOzF5cz9Z8RcIbFRRaaoQPxmplTxgFd1eEJ7Su4+1J8BJA+cxha9mvfquccTGcp0H+ZXnWrwMPiWbthMtBPY/9DfDXWAyf2rLASBxzJMrhr9wy7eAKeIqNcVlXzH/Q6g4Jxf5mNa0zJfcBTSC+GW9+PAOrs/rFsIp0hpSmq8hgtr56DldCIK0sh86qVjtt4hLJ4CXB7uyqxMEx9uV1jscnTSIlfdoJKIiP24XH8ownslRhgOqJqAyNSxmWnEsWgZfPNBVwsn85VTLpC3hEJKFvgYM3WSiYG8Qq9ui8NtZho+XddiCg9BlYD+MAJ48iwSq7UBZVCGwm4OlVZF8PWnJMf0s4X3NR41PpPP7O/S0X/jnPAGJwgeBvskUpNJu6JHufwoEoZfMXTeZez+UCbDLzZmaV4gex9ylXlIgnYhCLB0PpopFT13USaLmUD02Lx5wm+trivdvMI0XgdGfy+UOpHrziuEZA/2DehJS7zusf6dPSXmMU7EP2dmCHhWt5H6eauO1s5M="
    on:
      all_branches: true
  - provider: bintray
    skip_cleanup: true
    file: dist/.bintray-rpm.json
    user: mohierf
    key:
      secure: "E7gQCt2UO1zR3zc7UUQM9iJdF1ZrFUZd8i2ssuMhbXe3YrhmVQo20gXvB6si0U4G4iy5bHT3TB5r5Q7JBiyNazwgxHZb2XnNo368YrPEtVGZ6pOYC2/bL4MkjkFVPtOggtoTP57Mu/UN4MHhFmkjaSLfpLWPpBOFvHflOzF5cz9Z8RcIbFRRaaoQPxmplTxgFd1eEJ7Su4+1J8BJA+cxha9mvfquccTGcp0H+ZXnWrwMPiWbthMtBPY/9DfDXWAyf2rLASBxzJMrhr9wy7eAKeIqNcVlXzH/Q6g4Jxf5mNa0zJfcBTSC+GW9+PAOrs/rFsIp0hpSmq8hgtr56DldCIK0sh86qVjtt4hLJ4CXB7uyqxMEx9uV1jscnTSIlfdoJKIiP24XH8ownslRhgOqJqAyNSxmWnEsWgZfPNBVwsn85VTLpC3hEJKFvgYM3WSiYG8Qq9ui8NtZho+XddiCg9BlYD+MAJ48iwSq7UBZVCGwm4OlVZF8PWnJMf0s4X3NR41PpPP7O/S0X/jnPAGJwgeBvskUpNJu6JHufwoEoZfMXTeZez+UCbDLzZmaV4gex9ylXlIgnYhCLB0PpopFT13USaLmUD02Lx5wm+trivdvMI0XgdGfy+UOpHrziuEZA/2DehJS7zusf6dPSXmMU7EP2dmCHhWt5H6eauO1s5M="
    on:
      tags: true
